#ifndef WIFI_CREDENTIALS_LOCAL_H
#define WIFI_CREDENTIALS_LOCAL_H

#define WIFI_CRED_SSID1 "SSID1"
#define WIFI_CRED_PASSWORD1 "PASSWORD1"
#define WIFI_CRED_SSID2 "SSID2"
#define WIFI_CRED_PASSWORD2 "PASSWORD2"
#define WIFI_CRED_COUNT 2
#define WIFI_CRED_LOADED 1

/* Backward-compatible aliases (credential set #1) */
#define WIFI_CRED_SSID WIFI_CRED_SSID1
#define WIFI_CRED_PASSWORD WIFI_CRED_PASSWORD1

#endif
